const amenities = {
  scenicViews: ['River view', 'Valley view'],
  bathroom: [
    'Bathtub',
    'Hair dryer',
    'Cleaning products',
    'Shampoo',
    'Conditioner',
    'Outdoor shower',
    'Hot water',
    'Shower gel',
  ],
  bedroomAndLaundry: [
    'Washer',
    'Dryer',
    'Essentials',
    'Hangers',
    'Bed linens',
    'Extra pillows and blankets',
    'Iron',
    'Clothing storage: dresser and closet',
  ],
  entertainment: [
    'HDTV',
    'Sound system with Bluetooth and aux',
    'TV',
    'Record player',
    'JBL Bluetooth sound system',
    'Books and reading material',
  ],
  heatingAndCooling: [
    'Air conditioning',
    'Window AC unit',
    'Ceiling fan',
    'Central heating',
  ],
  homeSafety: [
    'Smoke alarm',
    'Carbon monoxide alarm',
    'Fire extinguisher',
    'First aid kit',
    'Security cameras on property',
  ],
  internetAndOffice: ['Wifi'],
  kitchenAndDining: [
    'Kitchen',
    'Refrigerator',
    'Cooking basics',
    'Dishes and silverware',
    'Mini fridge',
    'Freezer',
    'Dishwasher',
    'Induction stove',
    'Oven',
    'Hot water kettle',
    'Coffee maker: pour-over coffee',
    'Wine glasses',
    'Toaster',
    'Baking sheet',
    'Barbecue utensils',
    'Dining table',
  ],
  locationFeatures: ['Waterfront', 'Private entrance', 'Laundromat nearby'],
  outdoor: [
    'Private backyard – Not fully fenced',
    'Patio or balcony',
    'Backyard',
    'Fire pit',
    'Outdoor furniture',
    'Outdoor dining area',
    'BBQ grill',
  ],
  parkingAndFacilities: [
    'Free parking on premises',
    'Free street parking',
    'Free driveway parking on premises',
  ],
  services: [
    'Self check-in',
    'Smart lock',
    'Cleaning before checkout',
    'Pets allowed',
    'Long term stays allowed',
  ],
};

module.exports = amenities;
